name: ScalerApp
options:
  bundleIdPrefix: com.scaler
  deploymentTarget:
    iOS: 16.0

settings:
  base:
    DEVELOPMENT_TEAM: "" # Add your team ID here

targets:
  ScalerApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.scaler.app
    info:
      path: Sources/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    dependencies:
      - sdk: SwiftUI.framework
    
  ScalerAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/Unit
    dependencies:
      - target: ScalerApp
    
  ScalerAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UI
    dependencies:
      - target: ScalerApp
