name: Scaler
options:
  bundleIdPrefix: com.elusive
  deploymentTarget:
    iOS: 17.0

targets:
  Scaler:
    type: application
    platform: iOS
    sources:
      - Scaler
    settings:
      base:
        INFOPLIST_FILE: Scaler/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.elusive.scaler
    info:
      path: Scaler/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true 