version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 15.2.0
    steps:
      - checkout
      - restore_cache:
          key: pods-cache-{{ checksum "project.yml" }}
      - run:
          name: Install Dependencies
          command: |
            brew install xcodegen
            xcodegen generate
      - save_cache:
          key: pods-cache-{{ checksum "project.yml" }}
          paths:
            - ./Pods
      - run:
          name: Build and Test
          command: |
            xcodebuild clean test \
              -project Scaler.xcodeproj \
              -scheme Scaler \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test 